### ISSUE TITLE
Unsupported config option for services: 'index'

### ISSUE THREAD

**Issue by allenday** [sunsided/janusgraph-docker#4]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'index'

**Comment by sunsided** [comment]
Which version of Docker Compose are you using?

**Comment by allenday** [comment]
it was 1.18 from apt-get. I was able to pull from the official docker repo
and got it to work. now I am getting strange errors related to the startup
of gremlin.sh though, it seems that it cannot read or initialize the
database.

**Comment by sunsided** [comment]
This might be related to the `data` directory access rights. If it exists, try removing it first. 
I just stumbled upon a similar problem, while being at it, upgraded the repo to newer versions of the components - could you try if it works now?

```bash
docker-compose up --build --force-recreate
```

**Comment by allenday** [comment]
not sure if this is a related issue, but I noticed the `index` service was crashing. on the host system running `sysctl -w vm.max_map_count=262144` solved the problem (and correpsonding edit to `/etc/sysctl.conf`

**Comment by allenday** [comment]
also, `chmod -R 777 data`

**Comment by sunsided** [comment]
The `index` crashing should be solved with this block in the definition, specifically the `user` property:

```yaml
index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
     - "9200:9200"
     - "9300:9300"
    user: "1000"
    volumes:
     - ./data/elasticsearch/data:/usr/share/elasticsearch/data
```

I also forced the directories to exist on the repo in the first place, so there should be no need to re-own them every now and then.
